"""6954763.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ePEflGLKPxDlLavN-BSVASUl10k8vOzP
"""

from google.colab import files
uploaded = files.upload()

import numpy as np
import cv2
import math

class EEEM005_Coursework_Solution:

    def __init__(self):
        self.class_means = None
        self.class_vars = None
        self.class_log_priors = None
        self.classes = None
        self.n_classes = 0
        self.var_smoothing = 1e-9
        self.smooth_kernel = 7

    def _extract_features(self, image_bgr):
        img_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB).astype(np.float32) / 255.0
        r = img_rgb[:, :, 0]
        g = img_rgb[:, :, 1]
        b = img_rgb[:, :, 2]

        img_hsv = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2HSV).astype(np.float32)
        hue = img_hsv[:, :, 0] / 179.0
        sat = img_hsv[:, :, 1] / 255.0
        val = img_hsv[:, :, 2] / 255.0

        egi = 2.0 * g - r - b
        rg_ratio = (r - g) / (r + g + 1e-6)

        ksize = 5
        val_f32 = val.astype(np.float32)
        mean_v = cv2.boxFilter(val_f32, -1, (ksize, ksize))
        mean_v2 = cv2.boxFilter(val_f32 ** 2, -1, (ksize, ksize))
        var_v = np.maximum(mean_v2 - mean_v ** 2, 0.0)
        std_v = np.sqrt(var_v)

        feature_map = np.stack([r, g, b, hue, sat, val, egi, rg_ratio, std_v], axis=-1)
        features = feature_map.reshape(-1, feature_map.shape[2])
        return features.astype(np.float64)

    def _fit_gnb(self, X, y):
        self.classes = np.unique(y)
        self.n_classes = len(self.classes)
        n_features = X.shape[1]

        self.class_means = np.zeros((self.n_classes, n_features))
        self.class_vars = np.zeros((self.n_classes, n_features))
        self.class_log_priors = np.zeros(self.n_classes)

        N = len(y)
        for idx, cls in enumerate(self.classes):
            mask = (y == cls)
            X_cls = X[mask]
            self.class_means[idx, :] = X_cls.mean(axis=0)
            self.class_vars[idx, :] = X_cls.var(axis=0) + self.var_smoothing
            self.class_log_priors[idx] = math.log(mask.sum() / N)

    def _predict_gnb(self, X):
        N = X.shape[0]
        log_posteriors = np.zeros((N, self.n_classes))

        for idx in range(self.n_classes):
            mu = self.class_means[idx]
            var = self.class_vars[idx]
            log_likelihood = -0.5 * (
                np.sum(np.log(var))
                + np.sum(((X - mu) ** 2) / var, axis=1)
            )
            log_posteriors[:, idx] = self.class_log_priors[idx] + log_likelihood

        best_idx = np.argmax(log_posteriors, axis=1)
        return self.classes[best_idx]

    def _majority_vote_smooth(self, label_map):
        h, w = label_map.shape
        k = self.smooth_kernel
        pad = k // 2

        padded = np.pad(label_map, pad, mode='edge')
        votes = np.zeros((h, w, self.n_classes), dtype=np.int32)

        for dr in range(k):
            for dc in range(k):
                patch = padded[dr:dr + h, dc:dc + w]
                for idx, cls in enumerate(self.classes):
                    votes[:, :, idx] += (patch == cls).astype(np.int32)

        best_idx = np.argmax(votes, axis=2)
        return self.classes[best_idx]

    def model_training(self, Training_Image_Name, Training_Image_Mask_Name):
        image = cv2.imread(Training_Image_Name)
        mask = cv2.imread(Training_Image_Mask_Name)

        labels_2d = mask[:, :, 0].astype(np.int32)
        labels = labels_2d.ravel()

        X = self._extract_features(image)
        self._fit_gnb(X, labels)

    def model_testing(self, Testing_Image_Name, Testing_Image_Mask_Name):
        image = cv2.imread(Testing_Image_Name)
        h, w = image.shape[:2]

        X = self._extract_features(image)

        batch_size = 200_000
        N = X.shape[0]
        pred_labels = np.empty(N, dtype=np.int32)

        for start in range(0, N, batch_size):
            end = min(start + batch_size, N)
            pred_labels[start:end] = self._predict_gnb(X[start:end])

        label_map = pred_labels.reshape(h, w)
        label_map = self._majority_vote_smooth(label_map)

        mask_out = np.stack([label_map, label_map, label_map], axis=-1).astype(np.uint8)
        cv2.imwrite(Testing_Image_Mask_Name, mask_out)

        vis_map = (label_map * 50).astype(np.uint8)
        vis_colour = cv2.applyColorMap(vis_map, cv2.COLORMAP_JET)
        vis_name = Testing_Image_Mask_Name.replace('.png', '_visualised.png')
        cv2.imwrite(vis_name, vis_colour)


Model = EEEM005_Coursework_Solution()
Model.model_training("training_image.jpg", "training_mask.png")
Model.model_testing("testing_image1.jpg", "testing_mask1.png")
Model.model_testing("testing_image2.jpg", "testing_mask2.png")